language: go
go:
  - 1.4
  - tip
env:
  - GOARCH=amd64
  - GOARCH=386
install:
  - export PATH="$HOME/gopath/bin:$PATH"
  - go get -x github.com/tools/godep
  - go get -x -t -d
  - godep restore
script:
  - go test -x
